### ISSUE TITLE
没用spring，一定要依赖spring吗？

### ISSUE THREAD

**Issue by maoxianfly** [Baidu-ecom/Jprotobuf-rpc-socket#17]
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/beans/factory/InitializingBean
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.baidu.jprotobuf.pbrpc.server.RpcServiceRegistry.<clinit>(RpcServiceRegistry.java:46)
	at com.baidu.jprotobuf.pbrpc.transport.RpcServer.<init>(RpcServer.java:110)
	at com.baidu.jprotobuf.pbrpc.transport.RpcServer.<init>(RpcServer.java:118)

**Comment by jhunters** [comment]
普通的使用不需要Spring,  这个原因有一个log使用的类有问题，下个版本会修复

**Comment by jhunters** [comment]
erorr: protected static final Log LOGGER = LogFactory.getLog(RpcServiceExporter.class);
    corret: protected static final Log LOGGER = LogFactory.getLog(RpcServiceRegistry.class);

**Comment by jhunters** [comment]
该问题已在 2.24版本修复
